### ISSUE TITLE
ipp-test.test: I-19 Test - Unexpected status code

### ISSUE THREAD

**Issue by lpares12** [istopwg/ippeveselfcert#21]
Test I-19. Cancel-Job Operation (completed job), which tries to cancel a completed job results in `status-code = client-error-not-authenticated` when the first job of the queue was sent by another user.

The solution would be to modify the preceding test-case (I-18. Get-Jobs Operation) to query only jobs from the requesting user by adding `ATTR boolean my-jobs true`.

As I said, the problem is only visible when multiple clients are interacting with the same printer and the first job in the queue doesn't belong to the requesting user.

**Comment by michaelrsweet** [comment]
@lpares12 While the self-certification instructions do not specifically say this (but probably should...), the test scripts assume that you are testing the printer on an isolated network to prevent interference with the test results. And using "my-jobs" = 'true' might not be sufficient since the comparison is just the user name and not any more authenticated mechanism.

I will hold this bug open until the next IPP WG meeting so we can review it, but I'm guessing the resolution will be to log an issue against the self-cert manual and not try to make the script any "smarter".

**Comment by michaelrsweet** [comment]
Tentatively add something to the 1.0 update 3 README, until the 1.1 self-certification manual is completed.

**Comment by michaelrsweet** [comment]
For update 3:

[master b281156] Note that tests need to be run in isolation (Issue #21)

Will continue tracking this for v1.1.

**Comment by michaelrsweet** [comment]
@wifiprintguy What do you think about changing the tests? I don't think the my-jobs addition will make a significant difference over just running the test in isolation.

**Comment by michaelrsweet** [comment]
OK, well we've gone with the documentation change for both 1.0 Update 3/4 and the forthcoming 1.1 beta 1.
