### ISSUE TITLE
HTTP Upgrade test failed

### ISSUE THREAD

**Issue by Dingyuguan** [istopwg/ippeveselfcert#57]
When execut "B-5.1 HTTP Upgrade test" of dnssd-test.bat, after the certification tool sends OPTIONS request, the test Printer sends 101 Switching Protocols response. 
However,  the certification tool closes the current connection(does not start the ssl handshark), and re-send a OPTIONS request on a new connection.
The certification tool repeat above operations, and finally, this test failed.

![http upgrade](https://user-images.githubusercontent.com/66808389/85085036-25644700-b209-11ea-8cf9-7953d69e5b6c.png)

**Comment by michaelrsweet** [comment]
@Dingyuguan What version of the tools are you running?

There was a bug in the initial 1.1 Windows tools release (caused by a change in Secure Channel on Windows) that prevented the tools from establishing a TLS connection. The subsequent Update 1 on June 17, 2020 that is currently in testing - a link is available on the [self-certification portal](https://www.pwg.org/ippeveselfcert) - includes a workaround that fixes TLS support on Windows.

**Comment by Dingyuguan** [comment]
@wifiprintguy 
Thank you for your reply, the certification tools that I using is sw-ippeveselfcert11-20200522-windows.msi

**Comment by michaelrsweet** [comment]
@Dingyuguan Please download the latest tools and re-test.

**Comment by Dingyuguan** [comment]
@wifiprintguy
Thank you very much. This test has passed in the latest tools.

**Comment by michaelrsweet** [comment]
Great!
