### ISSUE TITLE
I-10: Allow "rangeOfInteger" values for "media-col-database" >> "media-size" members

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#89]
Some universal print systems allow "rangeOfInteger" syntax for the "x-dimension" and "y-dimension" members of "media-size" in "media-col-database" and "media-col-ready". The I-10 test currently fails if this syntax is supplied by the printer (typically roll-fed printers):

https://github.com/istopwg/ippeveselfcert/blob/69314943f695700a1223d13dc66880f6be4096aa/tests/ipp-tests.test#L436-L437

https://github.com/istopwg/ippeveselfcert/blob/69314943f695700a1223d13dc66880f6be4096aa/tests/ipp-tests.test#L443-L444

I-10.7 will also fail for similar reasons:

https://github.com/istopwg/ippeveselfcert/blob/69314943f695700a1223d13dc66880f6be4096aa/tests/ipp-tests.test#L1250-L1251

Change all instances of "media-size/y-dimension OF-TYPE integer" to be "media-size/y-dimension OF-TYPE integer|rangeOfInteger"  so that our IPP Everywhere Self-Certification tests won't conflict with other systems for roll-fed printers. (Clarifications to either 5100.7 or 5100.3 are coming.)

**Comment by michaelrsweet** [comment]
OK, so "media-col-default" MUST NOT contain rangeOfInteger values because it can be used directly, but "media-col-database" and "media-col-ready" MUST contain rangeOfInteger values if the corresponding "media-size-supported" collection values do - that's how the min/max sizes in "media-supported" and "media-ready" are mapped to the newer collection syntax. That's not specific to other "universal print systems", it is part of the definition of the various "media-col" attributes (even if it isn't 100% clear...)

So the fix here is to allow rangeOfInteger for "media-col-database" and "media-col-ready". "media-col-default" only allows integer.

**Comment by michaelrsweet** [comment]
Oh, and this blocks the release of the current 1.1 update 4 beta... :/

**Comment by michaelrsweet** [comment]
[master 93f8fd1] Fix IPP tests to allow the "x-dimension" and "y-dimension" member attributes to use the rangeOfInteger syntax to support roll and custom media.
