### ISSUE TITLE
Do not require document-numbers in overrides-supported

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippeveselfcert#9]
Per IPP WG meeting on May 9, 2016, the IPP tests should not require the document-numbers attribute be supported in "overrides-supported".

http://ftp.pwg.org/pub/pwg/ipp/minutes/ippv2-concall-minutes-20160509.pdf

**Comment by wifiprintguy** [comment]
In the discussion for PWG issue #30 on the PWG website (https://www.pwg.org/dynamo/issues.php?U30+P-1+S-2+I0+E0+Z0+Q) the consensus was to leave it as required because softening the requirement would subvert the normative language of 5100.6.  Given this, I think this issue ought to be closed.  So I'm closing it.
